language: c
sudo: required
install:
- sudo apt-get update
- sudo apt-get install lua5.1 luarocks p7zip-full python-sphinx
- sudo luarocks install penlight
- gem install github_changelog_generator
script:
- bash travis.sh
notifications:
  email:
    on_failure: always
    on_success: change
env:
  global:
  - GH_REF=github.com/keneanung/m-mf.git
  - GH_USER=keneanung
  - secure: SwT6gn7FQQpRvc4w2CE/+vbAxMtbaDc/vl8J8WO0/Drpx7axmyVD8AjRwDVe4g/AAt6eV+unfJ/dNzAgClt5xAZBLNRMw5qrXTxpt00bUUL2NEjAD2qbY1Rvd52ygUos6aqwZfH0WjOcHsS5m6k9be4W1/Kf7UK0ic/MjbYAmHApBPd8Pc5CWiZujYaxGZya7kXkSijWwET0oS22CX4veFEg54PM4SM6keFdrTCoOsdXuqZYNp5S82m2anBiawjcCmNImzcgYQs72KESmqqodyJN0xSlFoWT3EyOUQ3xrUSmlM5csy4HH04ZmSIaiDcUr5U1TARH+azXMjvDenzt4PFi2y3ISXU8lVrFryXjN4m4XEYQw7SyJjRAD7XXNxvtEOww5ZJtKxIsd8rGHCqAnb3HWhYZCpieWYIMeVECmwZQvZ/Rbc/N66rMFcYZh4sDIRytMKGqZSj/XGDLxWwGvfhXOyX9kJHkqCSEmLzxaJZojRAbLT6IWOgH1P6tYN2+9QGdT+f/xvUij1UW2acBTjDxYLLT7hc5elxT4P8BZeugl6A6+Wgpul3IoPnBiW2Zbos5EmZXqsdqxqr9iEMOxerrgfrJ+x8uPhPONeuRqxujfg938o5LMR9MwaUsWgBSdkM2cAuVxg7BSZjP4m9Nl7JJQtFTteS87wEzDVFKw8o=
deploy:
  provider: releases
  file_glob: true
  file: output/*.zip
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: ZCP8BWoyyb80xU/UIydQvLKWAkn+Ockyzl2mE6zMQl4CFOxkuEXLIMHjBEEzhsZx2PxlcCv1kAr0rdK7VPU06MwiDqPRYxtQveLNO47t08XdMjZyS9uqnAItjYNcQFCtFOhcfwAM6YnB1ravtUBuqHalJ/F0+jP2RgXRPWnImii94KvnJt/3+/M4Tbup9A1az7Fn+mlf1euNKw9WtT2ushmBAaNfOcRTCwTrXaZ8zoMeo65cbspzj8VO1r0fGJjO15qywG88oXJO3xAVKtOaxqcUQjWPDDJMNyycRLtpqZsEB/LMVPG5W2mXNlfhTlvl4BXM+N0s+PpGSujr99yAp32JLOQ0BxCDkONF8Oa9IivJII2Iqsn4PbLE/ldAHHgc7HQCB6ThGmcLErsClHzIBrSsQQ3a82R8Pe+qcDraOY5gFmjAfhDY2co3k9UjYJL1b0Hu+3xaa6C7aTdzhMXmw7+lnbIPD/NMi3krOoqC+UoSKSfPP/UVUxNyCBVKqIaWJPVH/OD/wOFfLhE+3OAfMZVBPxkXh1QsTFA5wXdYTsQyc/kWmznKMPkeB7UeyzGR6qRWkJbnHN3HshpEU3h0HYPldpwpjXD+PIlA/U0OLod/l8ykfQ9bv4mWVLEMNdJCshJQ1Jhd3q7g5MuNr+X1CpHNys5oqLkqCKK2xekG84o=
